### ISSUE TITLE
Figure out if we need the babel compile step

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/team-contribution-calendar#36]
Let's see the outcome of this: https://github.com/flexdinesh/npm-module-boilerplate/issues/5

**Comment by gomorizsolt** [comment]
As a side note, the repo also follows [**this**](https://stackoverflow.com/questions/29738381/how-to-publish-a-module-written-in-es6-to-npm) conventional pattern(src -> lib). Otherwise, it doesn't have any impact on the main topic of the issue. :)

Hopefully the owner will leave a clear answer, I'm also immensely curious about the reason for converting the JS codes back to ES5.

**Comment by thisismydesign** [comment]
Yep, we do: https://github.com/c-hive/guides/blob/master/js/package.md#esm
