### ISSUE TITLE
Use GH Actions CI

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/team-contribution-calendar#53]
Started in https://github.com/c-hive/team-contribution-calendar/pull/52/files

TODO:
- find or create action in [actions](https://github.com/c-hive/actions) to make a commit
  - input: pattern of files to git add, commit message
  - if a new action needs to be created i recommend to use a native JS action with `octokit`. you authenticate using a github token (which is part of the secret store by default) as seen here: https://github.com/babel/actions/blob/master/trigger-github-release/release.js (i think octokit can commit but i didn't check for sure)
- release to NPM, there should be an official action already available for this

**Comment by gomorizsolt** [comment]
I've been digging deeper into GH actions for a few days. It seems there's no custom action that's able to fulfill the requirements describe above. [`git-auto-commit-action`](https://github.com/stefanzweifel/git-auto-commit-action) is likely to be a potential candidate, but it doesn't expose a variable that'd accept file pattern(s) - though there's a single file that we'd like to commit & push to master, IMO it's an essential feature, otherwise additional files might be added to the commit unintentionally.

> release to NPM, there should be an official action already available for this

Check out [`actions/setup-node`](https://github.com/actions/setup-node), it's seemingly the proper solution for our case.

**Comment by gomorizsolt** [comment]
> This means you must include any package dependencies required to run the JavaScript code.

As per their [documentation](https://help.github.com/en/articles/creating-a-javascript-action#commit-and-push-your-action-to-github), it's mandatory to push `node_modules` alongside the source files. The other scenario is to use a compiler which outputs a single file - e.g. they suggest [`zeit/ncc`](https://github.com/zeit/ncc).

Which would fit the best our case? There's no doubt that the former case is simpler as that doesn't require further configurations.

**Comment by gomorizsolt** [comment]
Regarding to the input parameters, how about accepting an additional parameter to push the changes to a specific branch? This can default to `master` if the param is omitted. I'm not sure how much effort it involves, though it seems to be straightforward.

**Comment by gomorizsolt** [comment]
Leaving some further notes & questions.

> i think octokit can commit but i didn't check for sure

Even though `octokit` can [create](https://octokit.github.io/rest.js/#octokit-routes-git) commit(s), we still need a bash environment to stage the changes(i.e. `git add <pattern>`). Wouldn't it make sense to create a [docker based](https://help.github.com/en/articles/creating-a-docker-container-action) action so that we have access to this env? The drawbacks are:
- lack of knowledge of docker and its capabilities
- the [setup](https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L5-L19) flow seems to be complex

So I'd suggest forgetting this idea and sticking to the JS based action.

**Comment by thisismydesign** [comment]
We have access to shell via JS. We should not commit node modules. No need
for the branch param for now imo, let's keep the features incremental.

Wouldn't auto- commit work if we add things manually? Does it auto-add
everything?

**Comment by gomorizsolt** [comment]
> We have access to shell via JS.

Absolutely, but I was thinking of whether we really need JS for this simple action - that's why I brought up the idea of using a docker based action.

> No need for the branch param for now imo, let's keep the features incremental.

I share your views, it's also reasonable.

> Does it auto-add everything?

https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L33

Yes, it does. Unfortunately there's no way to bypass this somehow.

**Comment by thisismydesign** [comment]
JS (especially for a simple action) is preferable because it's faster.

Alright then, we can make our own action 🙂

**Comment by gomorizsolt** [comment]
> release to NPM, there should be an official action already available for this

@thisismydesign, could you add our NPM token to the [`Secrets`](https://github.com/c-hive/team-contribution-calendar/settings/secrets), please?

**Comment by gomorizsolt** [comment]
We've ended up with using [`git-auto-commit-action`](https://github.com/stefanzweifel/git-auto-commit-action) as the action now supports customizing the files to be added to the commit.

**Comment by gomorizsolt** [comment]
The [latest CI](https://github.com/c-hive/team-contribution-calendar/commit/7cdae6a877a20317974f33a77aa825bc26780c1e/checks?check_suite_id=287737369) didn't trigger the `commit-dist` job, presumably because of `github.ref == 'master'`.

**Comment by gomorizsolt** [comment]
It seems it's the wrong to syntax to conditionally execute jobs, see https://github.community/t5/GitHub-Actions/GitHub-Actions-branch-conditional/td-p/29794.

**Comment by gomorizsolt** [comment]
There's another issue with the `CI` workflow, that is, it fails when it tries to commit the changes.

https://github.com/c-hive/team-contribution-calendar/runs/281401583#step:5:15

Does the job share the installed dependencies among the steps? What I actually mean is that the [`Build & distify`](https://github.com/c-hive/team-contribution-calendar/blob/master/.github/workflows/ci.yml#L39) step installs the modules but they seem to be missing as per the error message. Either way, could anyone come up with a workaround to solve the issue? It'd be great to pass the `--no-verify` flag to skip the hooks but it's not (yet) supported by the action itself.

**Comment by thisismydesign** [comment]
> Does the job share the installed dependencies among the steps?

Yes, you can see this working in the test job. This looks like some sort of environment issue.

> It'd be great to pass the --no-verify flag

That'd make sense. As you already talked with the creator, could you ask him to support custom git params?

**Comment by thisismydesign** [comment]
I find environment related issues when searching for this:
https://github.com/desktop/desktop/issues/5036
https://github.com/plone/plone.recipe.codeanalysis/issues/55

If you can easily reproduce it with a bare-bone example you may also open an issue for pre-commit.

**Comment by gomorizsolt** [comment]
At last! [`git-auto-commit-action`](https://github.com/stefanzweifel/git-auto-commit-action) is now capable of including custom git params in the `git commit` command. Released `v0.2.0`, auto-publish to npm workflow works impeccably.
